name: genai-chat-db
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - azure-search-documents==11.5.2
    - openai==1.77.0
    - pyodbc==5.2.0
    - sqlparse==0.5.3
    - pytest==8.3.5
    - pylint==3.3.7
    - streamlit==1.45.0
    - dotenv==0.9.9