name: genai-chat-db
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - azure-search-documents==11.5.2
    - openai==1.77.0
    - pyodbc==5.2.0
    - fastapi[standard]==0.115.12
    - pydantic_settings==2.9.1
    - sqlparse==0.5.3
    - pytest==8.3.5
