name: Build docker image and deploy to Azure Container Apps

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
  CONTAINER_APP_NAME: ${{ vars.AZURE_CONTAINERAPP_NAME }}
  RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Run ONLY on main branch pushes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Set Github Short SHA
        run: echo "GITHUB_SHORT_SHA=$(echo '${{ github.sha }}' | cut -c1-7)" >> $GITHUB_ENV
      - name: Build docker image
        run: |
          docker build -t $ACR_LOGIN_SERVER/genai-chat-db:$GITHUB_SHORT_SHA .
          docker push $ACR_LOGIN_SERVER/genai-chat-db:$GITHUB_SHORT_SHA
    
  retag:
    name: Retag Image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') 
    steps:
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Set Github Short SHA
        run: echo "GITHUB_SHORT_SHA=$(echo '${{ github.sha }}' | cut -c1-7)" >> $GITHUB_ENV
      - name: Retag docker image
        run: |
          TAG=${GITHUB_REF##refs/tags/}
          docker pull $ACR_LOGIN_SERVER/genai-chat-db:$GITHUB_SHORT_SHA
          docker tag $ACR_LOGIN_SERVER/genai-chat-db:$GITHUB_SHORT_SHA $ACR_LOGIN_SERVER/genai-chat-db:$TAG
          docker push $ACR_LOGIN_SERVER/genai-chat-db:$TAG

  deploy:
    name: Deploy to Azure Container App
    runs-on: ubuntu-latest
    needs: retag
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_SP_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_SP_CLIENT_SECRET }}","subscriptionId":"${{ env.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ env.AZURE_TENANT_ID }}"}'
      - name: Deploy to container app
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            TAG=${GITHUB_REF##refs/tags/}
            az containerapp update \
              --name $CONTAINER_APP_NAME \
              --resource-group $RESOURCE_GROUP \
              --image $ACR_LOGIN_SERVER/genai-chat-db:$TAG