name: Build docker image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'       # Only trigger if files under src/ change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build docker image
        run: |
          docker build -t $ACR_LOGIN_SERVER/genai-chat-db:${{ github.sha }} .
          docker push $ACR_LOGIN_SERVER/genai-chat-db:${{ github.sha }}