name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          activate-environment: genai-chat-db
          environment-file: conda-env.yaml
          auto-activate-base: false
      - name: Run Pylint
        shell: bash -el {0}
        run: |
          pylint src --fail-under=7.0 --ignore=tests --disable=W1202
          